# Generated by Django 2.1.3 on 2018-11-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
